version: "3.8"
services:
  nginx:
    image: nginx:latest
    ports:
    - target: 80
      published: 80
      protocol: tcp
    deploy:
      replicas: 3
    volumes:
    - type: bind
      source: ./nginx.conf
      target: /etc/nginx/nginx.conf

  frontend:
    image: wkurtze/redshift-frontendimage:latest
    build: ./Frontend/final-project-frontend
    ports:
    - target: 3000
      published: 3000
      protocol: tcp
    deploy:
      replicas: 3

  backend:
    image: wkurtze/redshift-backendimage:latest
    build: ./Spring-Final-Project
    ports:
    - target: 8081
      published: 8081
      protocol: tcp
    deploy:
      replicas: 3
